### ISSUE TITLE
broken on Xcode 10.2 stack

### ISSUE THREAD

**Issue by bootstraponline** [bitrise-steplib/steps-remote-access-macos-ngrok#17] opened 2019-05-02 17:55 UTC
It looks like there's an issue on the Xcode 10.2 stack that prevents this step from working.

![image](https://user-images.githubusercontent.com/1173057/57096003-38a11400-6ce2-11e9-833c-f52998a45618.png)

**Comment by bitce** [comment] 2019-05-03 06:44
Hi @bootstraponline! Unfortunately yes, we are aware of this and currently investigating it, but thanks for reporting it nevertheless! :)

**Comment by godrei** [comment] 2019-05-16 11:41
Hi @bootstraponline, 
thanks for the issue report.
The issue is resolved so I will close this report.
I'll close this issue, but if you need more info/help just create a new issue!

**Closed by godrei** 2019-05-16 11:41 UTC
